/*
Copyright 2026 Dima Krasner

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package front

import (
	"strings"

	"github.com/dimkr/tootik/ap"
)

func idLink(id string) string {
	if parsed, err := ap.ParseID(id); err == nil && parsed.Kind == ap.PortableID && len(parsed.Canonical) < 512 {
		return strings.TrimPrefix(parsed.Canonical, "ap://")
	} else if err == nil && parsed.Kind == ap.PortableID {
		return ap.Slug(parsed.Canonical)
	}

	if len(id) < 80 {
		return strings.TrimPrefix(id, "https://")
	}

	return ap.Slug(id)
}

func containsID(ids ap.Audience, id string) bool {
	for other := range ids.Keys() {
		if ap.SameID(other, id) {
			return true
		}
	}

	return false
}

// linkParam converts a parameter generated by [idLink] to a value that can be compared with cid and slug columns.
func linkParam(arg string) string {
	if strings.HasPrefix(arg, "did:key:") {
		return ap.Canonical("ap://" + arg)
	}

	if strings.Contains(arg, "/") {
		return ap.Canonical("https://" + arg)
	}

	return arg
}
