name: build

on:
  workflow_call:
    inputs:
      version:
        type: string

jobs:
  analysis:
    permissions: {}
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends git ca-certificates
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: |
          go mod tidy -compat=`grep -m1 ^go go.mod | cut -f 2 -d ' '`
          go generate ./migrations
          go fix ./...
          git config --global --add safe.directory `pwd`
          git diff --exit-code
          go vet ./...
  static:
    permissions: {}
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim
    timeout-minutes: 5
    strategy:
      matrix:
        goarch: [amd64, arm64, arm, 386]
    steps:
      - uses: actions/checkout@v6
      - run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends ca-certificates
      - run: echo ${{ matrix.goarch }} > goarch
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum
            goarch
      - run: go generate ./migrations
      - run: |
          version="${{ inputs.version }}"
          echo "TOOTIK_VERSION=${version#v}" >> "$GITHUB_ENV"
      - run: CGO_ENABLED=0 GOARCH=${{ matrix.goarch }} go build -tags no_pprof -ldflags "-w -s -X github.com/dimkr/tootik/buildinfo.Version=${TOOTIK_VERSION}" -trimpath ./cmd/tootik
      - uses: actions/upload-artifact@v6
        with:
          name: tootik-${{ inputs.version }}-${{ matrix.goarch }}
          path: tootik
          retention-days: 1
  test:
    permissions: {}
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - flags: "-tags sqlite_mattn,fts5"
            race: true
            deps: "gcc libc6-dev"
          - flags: "-tags sqlite_modernc"
            race: false
            deps: ""
          - flags: "-tags sqlite_ncruces"
            race: false
            deps: ""
    steps:
      - uses: actions/checkout@v6
      - run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends ca-certificates ${{ matrix.deps }}
      - run: echo "${{ matrix.flags }}" > flags
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: |
            go.sum
            flags
      - run: |
          go generate ./migrations
          go test ./... -failfast -vet off ${{ matrix.flags }} ${{ matrix.race && '-race' || '' }}
  demo:
    permissions: {}
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends ca-certificates less
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go generate ./... && TERM=xterm-256color CGO_ENABLED=0 go run ./cmd/demo -record demo.cast
      - run: go tool termsvg export demo.cast -o demo.svg -m
      - uses: actions/upload-artifact@v6
        with:
          name: demo-${{ inputs.version }}
          path: ./demo.svg
          retention-days: 1
