name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:
  build:
    permissions: {}
    uses: ./.github/workflows/build.yml
    with:
      version: v99.99.${{ github.run_number }}
