name: edge

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
  workflow_dispatch:

jobs:
  edge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main' }}
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          build-args: TOOTIK_VERSION=99.99.${{ github.run_number }}
          tags: ghcr.io/${{ github.repository }}:edge
