name: image

on:
  workflow_run:
    workflows: [build]
    types: [completed]
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}:latest